export { default as apiRoutes } from './00-api.routes'
export { default as ecommerceRoutes } from './01-ecommerce.routes'
export { default as errorRoutes } from './00-error.routes'
export { default as moviesRoutes } from './02-movies.routes'
export { default as userRoutes } from './users.routes'
